# This srv request specifies a global pose of an image, through the naming convention and a global pose is returned.
# Per default the imagePath is used. However, if it is empty, it is recreated from the given image properties.
# If the 'sessionID' is empty, the current session is used.
# If the 'path' is empty, the current working directory is used.
# The naming convention is specified elsewhere. However, as a rule of thumb: "%sid%i-%i.%s" Ex. /home/john/id1-12.jpeg

string imagePath
uint8 sessionID
uint8 mobotID
uint8 imageID
string path
---
geometry_msgs/Pose pose