# This srv request specifies an image, through the naming convention and a compressed image is returned.
# 'imagePath' contains the filepath and filename. Otherwise it is created from
# 	the data below.
# If 'path' is empty, the default directory is used.
# 'pose', if the pose of the image should be returned
# The naming convention is specified elsewhere. However, as a rule of thumb:
# 	"%ssession-%i/mobotID%i-%i.info" Ex. /home/john/session-1/mobotID2-12.info
# Null is returned if image is not found.

string imagePath

string savePath
uint8 sessionID
uint8 mobotID
uint8 imageID
string encoding
---
mobots_msgs/ImageWithDeltaPoseAndID image
string error
