# This srv request specifies an image and a compressed image is returned.
# type defines which information is requested.(Both - 0, Pose - 1)
# rel_pose - Relative, abs_pose - Absolute, del_pose - delta
# error codes are found in map_visualization/src/image_store/error_status.cpp

mobots_msgs/ID id
int8 type
---
sensor_msgs/Image image
geometry_msgs/Pose2D del_pose
geometry_msgs/Pose2D rel_pose
geometry_msgs/Pose2D abs_pose
int8 error
